# Generated by Django 3.1.2 on 2020-10-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('game', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('price', models.FloatField(default=0)),
                ('owners', models.CharField(max_length=100)),
                ('developer', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('average_playtime', models.IntegerField(default=0)),
                ('median_playtime', models.IntegerField(default=0)),
                ('metascore', models.IntegerField(default=0)),
            ],
        ),
    ]
