# Generated by Django 3.1.2 on 2020-11-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201029_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='average_playtime',
            field=models.IntegerField(default=0, verbose_name='Tempo médio de jogo'),
        ),
        migrations.AlterField(
            model_name='review',
            name='developer',
            field=models.CharField(max_length=100, verbose_name='Desenvolvedor'),
        ),
        migrations.AlterField(
            model_name='review',
            name='game',
            field=models.CharField(max_length=100, verbose_name='Jogo'),
        ),
        migrations.AlterField(
            model_name='review',
            name='median_playtime',
            field=models.IntegerField(default=0, verbose_name='Tempo mediano de jogo'),
        ),
        migrations.AlterField(
            model_name='review',
            name='metascore',
            field=models.IntegerField(default=0, verbose_name='Metascore'),
        ),
        migrations.AlterField(
            model_name='review',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='review',
            name='owners',
            field=models.CharField(max_length=100, verbose_name='Donos'),
        ),
        migrations.AlterField(
            model_name='review',
            name='price',
            field=models.FloatField(default=0, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='review',
            name='publisher',
            field=models.CharField(max_length=100, verbose_name='Publicador'),
        ),
        migrations.AlterField(
            model_name='review',
            name='release_date',
            field=models.CharField(max_length=100, verbose_name='Data de lançamento'),
        ),
    ]
